Repository supabase/wrappers, pull requests merged in 2024-01, with the labels that each got.

#217 docs: add community wrappers contribution docs
  docs/contributing.md
Labels: documentation

#216 feat: upgrade S3 FDW dependencies
  wrappers/Cargo.lock
  wrappers/Cargo.toml
  wrappers/src/fdw/s3_fdw/mod.rs
  wrappers/src/fdw/s3_fdw/parquet.rs
  wrappers/src/fdw/s3_fdw/s3_fdw.rs
Labels: s3

#215 feat: add redis foreign data wrapper
  README.md
  docs/index.md
  docs/redis.md
  mkdocs.yaml
  supabase-wrappers/src/lib.rs
  wrappers/.ci/docker-compose.yaml
  wrappers/Cargo.lock
  wrappers/Cargo.toml
  wrappers/README.md
  wrappers/src/fdw/mod.rs
  wrappers/src/fdw/redis_fdw/README.md
  wrappers/src/fdw/redis_fdw/mod.rs
  wrappers/src/fdw/redis_fdw/redis_fdw.rs
  wrappers/src/fdw/redis_fdw/tests.rs
Labels: redis
